### ISSUE TITLE
Periods in cookie's name

### ISSUE THREAD

**Issue by jcamachott** [tasianmedia/cookieJar#3]
The getCookie does not work if your cookie has a period in the name e.g. if your cookie is named "local.user", however, setCookie works fine with cookies named that way.

**Comment by davidpede** [comment]
Thanks for reporting, will look into this

**Comment by jcamachott** [comment]
Thanks. Quick OT question - when I use &tpl... what do I use as the placeholder inside? I tried [[+value]] and that did not work.

**Comment by davidpede** [comment]
Can't replicate the placeholder issue, [[+value]] works for me. What's your snippet call?

**Comment by davidpede** [comment]
Have looked into this and the reason you can't use full stops (periods) in the cookie name is due to the Register Globals setting, which takes all $_POST, $_GET, $_COOKIE vars and sets them to real variable names. As you say, they can be set but not accessed by php.

Explained here: http://harrybailey.com/2009/04/dots-arent-allowed-in-php-cookie-names/

**Comment by davidpede** [comment]
Due to this being a PHP/Server setting issue I'm going to close this.

Thanks for raising though.

**Comment by jcamachott** [comment]
Thanks David
